version: "3.7"

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    restart: always
    container_name: backend-calendar
    env_file:
      - ./.env
    depends_on:
      - mongo

  nginx:
    container_name: nginx-calendar
    build:
      context: ./nginx
      args:
        NGINX_CONFIG: "nginx.conf"
    depends_on:
      - backend
    ports:
      - "80:80"
