version: "3.7"

services:
  db:
    container_name: db-calendar
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: calendar

  backend:
    build:
      context: ./backend
    container_name: backend-calendar
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    container_name: nginx-calendar
    build:
      context: ./nginx
      args:
        NGINX_CONFIG: "nginx.conf"
    depends_on:
      - backend
    ports:
      - "80:80"
