version: "3.7"

services:
  backend:
    volumes:
      - ./backend:/backend
    ports:
      - 5000:5000

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/db
